<?php

/**
 * @file
 * Functions to support theming.
 */

function dasjo_preprocess_html(&$variables) {
  drupal_add_html_head_link(array(
    'href' => 'http://fonts.googleapis.com/css?family=Titillium+Web:300,600,300italic|Quantico',
    'rel' => 'stylesheet',
    'type' => 'text/css',
  ));
}

function dasjo_preprocess_block(&$variables) {
}

function dasjo_preprocess_node(&$variables) {
  // print_r($variables);
  $i = 1;
}




