features:
  logo: 0
  name: 1
  slogan: 0
  node_user_picture: 0
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 0
  main_menu: 1
  secondary_menu: 0
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 1
  path: ''
favicon_upload: ''
